### ISSUE TITLE
Does not work when not listed as a dependency (using --save) in package.json

### ISSUE THREAD

**Issue by seshaljain** [jaredly/hexo-admin#101]
The process:

1. `hexo init blog`
2. `cd blog`
3. `npm install hexo-admin`
4. `hexo server`

 \*goes to localhost:4000/admin\*
**Cannot GET /admin/**

Did some digging, if I do
`npm install hexo-admin --save` in step 3), hexo-admin works perfectly. I missed the `--save` flag when I first installed it, was quite frustated for some time. Just wanted to ask _why_ does that happen. Does it have something to do with node?

System arch : Ubuntu 16.04 x64
node            : 4.7.0
npm             : 4.1.1

**Comment by PirtleShell** [comment]
It has to do with how Hexo loads plugins. It determines what plugins to load by looking for `hexo-` prefixed packages in your `package.json`. The `--save` in the install command adds it for Hexo to find.

From [hexo's plugin docs](https://hexo.io/docs/plugins.html):
> You’ll also need to list your plugin as a dependency in the root package.json of your hexo instance in order for Hexo to detect and load it.

**Comment by seshaljain** [comment]
Great, thanks!
