### ISSUE TITLE
Alway Invalid salt revision

### ISSUE THREAD

**Issue by tunacon** [jaredly/hexo-admin#103]
I don't know why it's alway say Invalid salt revision when i enter correct password for example password: 1234 
hash: $2y$10$hH3QeISDuv5HkgKLMo0C4Owsp6lyVJxjP7p3gcVTWKTRlgj7uZZia

I already test on this site https://bcrypt-generator.com and it's said Good hash! :) so what happen anyone know?

**Comment by hollsteinm** [comment]
+1 I am having the same issue as well. Even changed the $2y to $2a to see if it was something to do with this issue: https://github.com/ircmaxell/password_compat/issues/49

**Comment by tmirun** [comment]
+1 Same problem

**Comment by PirtleShell** [comment]
The hash generator used by the backend no longer jives with the one used on the website generator. I made a PR that removes the need to have a `password_hash` at all. We'll have to wait for @jaredly to pull and publish.

As a temporary fix, generate a proper hash for your config file by running the following in your hexo instance's directory:
```js
$ node

> const bcrypt = require('bcrypt-nodejs')

> bcrypt.hashSync('your password secret here!')
//=> '$2a$10$8f0CO288aEgpb0BQk0mAEOIDwPS.s6nl703xL6PLTVzM.758x8xsi'
```

Copy the hash to `admin.password_hash` in your `_config.yml`.

**Comment by tastomy** [comment]
Thank you @PirtleShell , now its working.

if anyone not have bcrypt-nodejs module just 

> npm install bcrypt-nodejs --save

and try again.

**Comment by PirtleShell** [comment]
Hexo admin now includes a page to generate the `admin` section of you config.
