### ISSUE TITLE
Code preview problem

### ISSUE THREAD

**Issue by xbotao** [jaredly/hexo-admin#106]
## working environment
- windows 10
- hexo-admin @2.1.0 ( the github verion )
- Chrome 55.0

---

### writing
![writing-code](https://cloud.githubusercontent.com/assets/6964173/22198452/8911cf1c-e191-11e6-82df-d27e37f9df74.png)

### after writing
![previewcode](https://cloud.githubusercontent.com/assets/6964173/22198471/9f4a1e38-e191-11e6-8fcd-4120814bb93f.png)

![preview](https://cloud.githubusercontent.com/assets/6964173/22198470/9f075cc4-e191-11e6-8761-d739b96625a1.png)

why the code preview different ? And the highlight is not enabled when writing the posts.

**Comment by PirtleShell** [comment]
When editing, only markdown is rendered in the preview. Code blocks are not run through a highlighter.

The initial preview viewed from the posts list or before any edits are made in the editor are generated from the actual HTML rendered by Hexo.

There are performance reasons to do it this way, but we might be open to using a different renderer. Currently, live previews are generated with [marked](https://github.com/chjj/marked).

**Comment by xbotao** [comment]
I add highlight to preview code during editing follow [this](https://github.com/newbiebt/hexo-admin/blob/master/AddHighlight.md) and push it to  [newbiebt/hexo-admin](https://github.com/newbiebt/hexo-admin). I donnot know how to have a **pull request**, please add it. @PirtleShell
