### ISSUE TITLE
Code preview problem2 - long code line

### ISSUE THREAD

**Issue by xbotao** [jaredly/hexo-admin#107]
## working environment
- windows 10
- hexo-admin @2.1.0 ( github version )
- chrome 55.0

## code line is long

![long code](https://cloud.githubusercontent.com/assets/6964173/22199039/29a662ce-e194-11e6-963a-577326dd6868.png)
![longcode2](https://cloud.githubusercontent.com/assets/6964173/22199040/29cb8798-e194-11e6-84ae-712be1ab34bb.png)

### After close and open again
when Editing the posts
![afteropenedit](https://cloud.githubusercontent.com/assets/6964173/22199238/07a0117e-e195-11e6-95f3-04b23c075a82.png)

## All posts line is short

If all the post line is short, the posts list page will like the follow.

![short](https://cloud.githubusercontent.com/assets/6964173/22199396/ae4e5dc8-e195-11e6-8739-8fe082da4e95.png)

**Comment by PirtleShell** [comment]
Let me know if that didn't fix it. I was able to reproduce your problem and it went away when I gave the editor a `max-width` of 100%.

**Comment by newbiebt** [comment]
It's OK when the code line is long by your fixed when the code is long. Thanks!

Another problem, If I could let the lists page's preview fill the right area.
![short](https://cloud.githubusercontent.com/assets/13112518/22217065/8445e112-e1dc-11e6-9041-431cf35438fc.png)

**Comment by newbiebt** [comment]
I add the highlight to hexo-admin editing follow [this](https://github.com/newbiebt/hexo-admin/blob/master/AddHighlight.md). (my another account).
Highlist is OK, But the code preview's line-height is big and I don't konw how to fix this.
Could you help me to fix this?

![default](https://cloud.githubusercontent.com/assets/13112518/22232980/c5fe8a8c-e227-11e6-9590-d0300fea12b0.png)

**Comment by xbotao** [comment]
It's OK when the code line is long by your fixed. Thanks!

Another problem, if the all the posts line is short.
It could be fixed by add the `width: 100%;` to **posts_content**, please add this @PirtleShell .
```
.posts_content {
  overflow: auto;
  padding: 30px;
  width: 100%;
}
```

![short](https://cloud.githubusercontent.com/assets/13112518/22217065/8445e112-e1dc-11e6-9041-431cf35438fc.png)
