### ISSUE TITLE
File name could be modified while editing the post

### ISSUE THREAD

**Issue by mujinjun** [jaredly/hexo-admin#11]
Sometime I wanna give a meaningful name to my new post,which is not like the title of the post.Currently I use the mv cmd to change the post's name in the shell. I know it's not necessary ,but I think it could be perfect with the name-modifying function.

**Comment by bobchennan** [comment]
I have implemented a simple deploy page. It calls a script specified in the yml configuration and takes the first parameter as commit log.

Added a pull request.

**Comment by PirtleShell** [comment]
This has been added in https://github.com/jaredly/hexo-admin/pull/105
