### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by PirtleShell** [jaredly/hexo-admin#112]
Hi there @jaredly,
Can we push the latest master to `npm`?

Thanks!

**Comment by rangeryu** [comment]
spent lots of time on troubleshooting... and finally it turns out that hexo-admin was not updated to npm for long time, event the version number is the same 2.1.0  

Many thanks for the project.

**Comment by jaredly** [comment]
wow sorry for the delay on this. just published 2.2.0.
 @PirtleShell do you want to be added as a collaborator on npm? What's your npm username?

**Comment by PirtleShell** [comment]
No worries!

That'd be awesome. On npm my username is also pirtleshell.
