### ISSUE TITLE
Can we add tool-tips to buttons?

### ISSUE THREAD

**Issue by mvxt** [jaredly/hexo-admin#114]
Thank you Linus Torvalds for inventing Git.

I clicked to edit a post, but then changed my mind. I know now we should just use the back button, but I didn't realize the "X" next to the settings button was to actually delete the post, not cancel the editing. Any chance we can add tooltips so that people know exactly what each button does?

**Comment by PirtleShell** [comment]
They are in the current github version. If you install it instead of the npm version you will see them.
