### ISSUE TITLE
Deleted files source/_discarded have first letters truncated

### ISSUE THREAD

**Issue by mvxt** [jaredly/hexo-admin#115]
Super minor issue and probably a quick fix, but when you delete a post from the hexo admin, it moves this post to a _discarded folder. For whatever reason, it chops off the first letter of the file name.

_**To Reproduce:**_
- Make a new post with any name
- List the file(s) in source/_posts to see the full filename and note what it is
- Open hexo admin and delete that post
- List the file(s) in source/_discarded and note how the first letter is chopped off.

**Comment by PirtleShell** [comment]
Thanks for the bug report! I can confirm this happens. It's probably an index error that occurred when I edited the file naming logic in #105.

I'll look into it when I get a chance.

Thanks again!
