### ISSUE TITLE
Better UX of delete button 

### ISSUE THREAD

**Issue by fadehelix** [jaredly/hexo-admin#118]
I found few ux issues with "delete post" button:

1. Cross icon may suggest that this is something like "close editing" rather than "delete",
2. There is no confirmation popup if you click the button
3. Currently the "delete" is the first editing option. I assume that the most important is  the "gear", then "unpublish" button.

The problem is that we can't undo delete, so the option requires better ux in order to avoid user's confusion and fear.

**Comment by jaredly** [comment]
actually, you can undo delete -- delete just moves the file into "_discarded", and if you move it back into `_drafts`, all is well. However, there's no UI for that.

**Comment by fadehelix** [comment]
@jaredly I know about _discarded, but if a user uses admin panel then he probably don't want to mess with files.
I made something like that on my fork (I'm going to improve style and, maybe, message ;)):
![hexo-admin-remove-post-ux](https://cloud.githubusercontent.com/assets/218922/23238571/db737e02-f962-11e6-96b6-e3d3e0cb6675.png)

**Comment by PirtleShell** [comment]
That looks like a great idea to me. I would prefer the "cannot be undone" to be more along the lines of "will be moved into _discarded folder". But confirmation on delete is a solid feature.

**Comment by fadehelix** [comment]
Thanks for feedback guys, I changed the text following your advices and now it look like this:

![hexo-admin-remove-post-ux-2](https://cloud.githubusercontent.com/assets/218922/23259148/f85c7104-f9cb-11e6-80f7-cfb3f1b23037.png)

**Comment by jaredly** [comment]
Excellent! go ahead and make a pull request with that

**Comment by PirtleShell** [comment]
we have satisfied the UX gods.
