### ISSUE TITLE
can only used in local

### ISSUE THREAD

**Issue by guankai** [jaredly/hexo-admin#119]
I setup this plugin, and use the command `hexo server d`, I can open the admin-ui and all the functions ok，but when git to github,I can not open by the url `domain.github.io/admin`，can someone help to deal with it.thank you

**Comment by yfsoftcom** [comment]
Only static files can run on github pages ! like html , js ,css

hexo-admin need nodejs support

**Comment by jaredly** [comment]
here's a previous issue https://github.com/jaredly/hexo-admin/issues/76
I should really add a section to the readme

**Comment by jaredly** [comment]
ok, added a section here https://github.com/jaredly/hexo-admin/blob/master/Readme.md#local-use-vs-deployment
