### ISSUE TITLE
Delete a publish post doesn't work

### ISSUE THREAD

**Issue by tunacon** [jaredly/hexo-admin#123]
When I delete a publish post it will disappear from hexo admin but still indicated on web page. I checking a post file it's already in 'source/_discarded/'. It will disappear on web page since I restart a "hexo server" and "hexo clean, hexo generate".

What's happen, it's a bug ?

**Comment by jaredly** [comment]
This is a safety feature to save you if you delete something by accident. You can delete the post from `_discarded` and it will be gone for good

**Comment by fadehelix** [comment]
I tried to recreate possible bug, but after `hexo clean && hexo generate` deleted post disappeared properly from web page. 
I use newest version of hexo-admin.

**Comment by tunacon** [comment]
So If I understand correctly, a post that I was deleted shouldn't disappeared after `hexo clean && hexo generate` right?

**Comment by PirtleShell** [comment]
There's no need to restart, the post gets moved to _discarded and is no longer served. To delete the files from your machine completely, you need to delete _discarded.

**Comment by tunacon** [comment]
I uploaded a video for showing a case that happen with me 

https://youtu.be/dQcAy2vvulA

**Comment by PirtleShell** [comment]
Ah, yes. I see what you mean, and the same happens to me. We probably need to add logic to delete it from Hexo's database. Even though it's removed from the served file system, the generated post and it's contents all still exist within hexo's database. Let's look into if there is a better way in Hexo's API to remove a post fully from the database.

**Comment by tunacon** [comment]
@PirtleShell oh, I see thank you for explain about hexo's database 👍

**Comment by williamchanrico** [comment]
Apparently, the current working post-removal flow is to first **unpublish**, and **remove** the post then.
 
How about restrict the post removal before unpublishing it? or making the remove button also trigger unpublish?
