### ISSUE TITLE
Add "Update" button next to "Unpublish" one. 

### ISSUE THREAD

**Issue by fadehelix** [jaredly/hexo-admin#127]
This enchantment has very low priority (even for "usability extremist" like me ;) but would be nice to make post update more intuitive by add "Update" button next to "Unpublish".

For now we have only the latter and it's pretty obvious that, in order to save changes, I have to click "Unpublish" and then "Publish", but I noticed a moment of confusion when I wanted to update a post first time because I asked myself what could happen when I click "Unpublish".

**Comment by PirtleShell** [comment]
The post is automatically saved whenever changes are made. There is no update button because what is being show is what is saved in the file.

Clicking unpublish will simply move your current post from `_posts` to `_draft`.

**Comment by fadehelix** [comment]
Ok, thanks, I didn't notice autosave.
