### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by NovaSurfer** [jaredly/hexo-admin#13]
What about password protection for this plugin?

**Comment by wodCZ** [comment]
+1

**Comment by jaredly** [comment]
What do you envision this looking like?
I see a few options.

The easiest is probably to have a hashed password entered as a config variable and then you input the password when you get to /admin, and the hashed version of the password is sent as token auth or something.

SHA3 for javascript is [available here](https://code.google.com/p/crypto-js/#SHA-3)

**Comment by wodCZ** [comment]
Storing strongly hashed password in config would be good enough and easy to implement I think.
Also, please consider adding admin path as another variable to config file. That shouldn't be hard and you'll get some security through obscurity.

**Comment by jaredly** [comment]
mmmm I'd hope that no one would rely on that... but yeah, easy to add.
PRs welcome :) if not I'll probably get to it in the next few weeks.

**Comment by wodCZ** [comment]
I'd like to PR, but I'm PHP dev, not experienced in JS - consumer only, sorry :)

**Comment by bourvill** [comment]
+ 1 for login protection

**Comment by yarax** [comment]
I've sent a pull request with base authentication. See, please

**Comment by yarax** [comment]
Anyone alive here?)

**Comment by jaredly** [comment]
Thanks to @yarax for getting this going! Password protection is now available in the just-published `0.3.0` version on npm. Let me know how it goes! Information on how to get it running is available in the Readme.

**Comment by bourvill** [comment]
Amazing ! Thx!
