### ISSUE TITLE
How to add a button in editing page?

### ISSUE THREAD

**Issue by xbotao** [jaredly/hexo-admin#131]
I want to add a button near the Check button. And push the post to other blogs which support **metaweblog API** by click this button. But I am not good at `js` and in a trouble.

---

1. I can add a button with follow code, but i donnot konw which `fa icon` can be used.
```
          <button className="editor_checkGrammar" title="Check for Writing Improvements"
                  onClick={this.onCheckGrammar}>
            <i className="fa fa-check-circle-o"/>
          </button>}

/* add the follow code*/
          {!this.props.isPage &&
          <button className="editor_push2cnblog" title="Publish to cnblogs"
                  onClick={this.onCheckGrammar}>
            <i className="fa fa-dot-circle-o"/>
          </button>}
```

2. I want to publish the post to metaweblog, I donnot konw how to add the function?

---

Could you tell me how to add a function? The function should run in the `api.js`  and can get the post's content.

**Comment by jaredly** [comment]
1) here's a list of all the [fontawesome icons](http://fontawesome.io/icons/)
2) That sounds like a complex bit of functionality!
I don't know what format the metaweblog API expects, but I imagine you'll have to ask hexo to essentially render the html of the post for you (I imagine there's a function for it, but it might take a bit of work), and from there I imagine you can use an ajax library to call the api endpoints you need. Looks like there's a [node module](https://www.npmjs.com/package/metaweblog-api) for that.

Another way of going about it (and this might be better) would be to make a separate hexo plugin that just handles the metaweblog integration, and gives you a command (like `hexo mweb` or something) that will do what you want.

**Comment by xbotao** [comment]
Thanks！
 Aboout `metaweblog API `, I need publish the **raw markdown**, and there is a node module to pubulish sth. to a metaweblog blog. I just donnot konw how to add a function in `api.js` to response the button's click  event.

**Comment by jaredly** [comment]
Oh cool, that makes it somewhat easier.

- add an api method here, similar to "deploy" [here](https://github.com/jaredly/hexo-admin/blob/master/client/api/rest.js#L47)
- then call it from the UI code, in an onclick handler from the button you add, as in [here](https://github.com/jaredly/hexo-admin/blob/master/client/deploy.js#L29). The data you pass in should be the markdown contents of the post
- then you add a `use("name-of-your-endpoint",` to api.js, as [here](https://github.com/jaredly/hexo-admin/blob/master/api.js#L407), and in that handler you take the markdown contents and call whatever metaweblog nodejs package you want
