### ISSUE TITLE
What about a description input on post setting?

### ISSUE THREAD

**Issue by tangwz** [jaredly/hexo-admin#137]
Now The post writing page can set Date, Author, Tags and Categories. But sometimes also need set **description.**

**Comment by fadehelix** [comment]
@tangwz what do you mean by description?

**Comment by pirtleshell** [comment]
This can now be accomplished with metadata. Simply add this into your `_config.yml`:
```
metadata:
  description: Default description here!
```
Now description will be an available field in the settings.
