### ISSUE TITLE
Funny way to resolve one issue with "load failure"

### ISSUE THREAD

**Issue by wukong2** [jaredly/hexo-admin#138]
1st, after install and setup; load failure
_ERROR Plugin load failed: hexo-admin
Error: [Hexo Admin]: the provided password_hash looks like an md5 hash -- hexo-admin has switched to use bcrypt; see the Readme for more info._
2nd, try to follow up steps without change, still fail several time
3rd, remove blank, successfully done
after one item change, see below error 
_FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 76, column 9:
      secret: a secret something
            ^_
_FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 76, column 9:
      secret: whatsthissecret
            ^_

below is last update
admin:
  _username:abcdefg
  password_hash:be121740bf988b2225a313fa1f107ca1 
  secret:whatsthisdump_

can anyone suggest anything wrong here? remember no such problem in the past

thanks

**Comment by fadehelix** [comment]
I think this issue is the same as #128

**Comment by pirtleshell** [comment]
As the error suggests, you aren't encrypting your password with the proper hash function. Try starting hexo without that info in your config, going to the Settings, and then click "Setup authentication here".
