### ISSUE TITLE
What is the use of _admin-config.yml?

### ISSUE THREAD

**Issue by amithealthist** [jaredly/hexo-admin#144]
Can anyone tell me the use of _admin-config.yml? And how to write the config file for admin? I need help to add more options to settings in an editor like description, cover_image_url etc.

**Comment by pirtleshell** [comment]
that config file is for the settings that are set in the Settings tab.

it sounds like what you want isn't "settings" but rather, [custom post metadata](https://github.com/jaredly/hexo-admin#custom-post-metadata). these type of things are added in your regular hexo config file
