### ISSUE TITLE
Switch to bcryptjs

### ISSUE THREAD

**Issue by Haocen** [jaredly/hexo-admin#147]
Currently server will suffer a little thanks to hashing long password, this package provide better performance:

https://www.npmjs.com/package/bcryptjs

**Comment by pirtleshell** [comment]
hi there, sorry for the delay.

thanks for suggesting the more performant package! however, hexo-admin is currently only setup to handle one user account. surely the performance on hashing a password isn't that inhibiting at this scale? we'd happily accept a PR if you implemented it, but it's not a very high priority IMO.
