### ISSUE TITLE
layout issue in Safari

### ISSUE THREAD

**Issue by zhangyee** [jaredly/hexo-admin#15]
![2014-12-26 10 47 06](https://cloud.githubusercontent.com/assets/1904821/5555533/72aecd32-8cee-11e4-92d8-23105f6d927f.png)
As shown in the screenshot above, Safari Browser can't render the hexo-admin layout correctly. But It's be OK in Chrome.
![2014-12-26 10 47 15](https://cloud.githubusercontent.com/assets/1904821/5555544/f4fa8556-8cee-11e4-8b99-4839e14e5763.png)

hexo-admin "version": "0.1.3",
Safari: 8.0 10600.1.25.1

**Comment by lsmoura** [comment]
On OSX El-Capitan this is not an issue. I believe this issue can be closed.
