### ISSUE TITLE
Error: spawn hexo ENOENT

### ISSUE THREAD

**Issue by donaf** [jaredly/hexo-admin#155]
first

the error is `admin.deployCommand`

so i add 
`deployCommand: hexo`
into"_config.html"

 after save

i input "Deploy/hello word",and click the button of "deploy"

it's tips  `“Error: spawn hexo ENOEN”`

sorry,my english is not very good,wish you will understand what's the meaning.

**Comment by pirtleshell** [comment]
hi @donaf, `ENOENT` means it can't the `hexo` binary. try changing it to `node_modules/.bin/hexo` or the path to your global `hexo` (whatever is returned by `which hexo` from the terminal when inside your project root).

additionally, the command `hexo` by itself will do nothing but return the help text. maybe you mean `hexo build`? what are you trying to do when you deploy?
