### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Boby-Zhang** [jaredly/hexo-admin#156]
serveStatic(path.join(__dirname, '../www', 'login'))(req, res);
 to 
var serve = serveStatic(path.join(__dirname, '../www', 'login'));
 serve(req, res,next);

**Comment by benjaminbra** [comment]
You should explain the bug and what this correction will change.

**Comment by pirtleshell** [comment]
Feel free to make a PR for the code change. However, in it's current state it isn't exactly a bug, so I'm closing this issue.
