### ISSUE TITLE
about change the pasted image file path

### ISSUE THREAD

**Issue by Cicinnus0407** [jaredly/hexo-admin#159]
In hexo-admin setting,I can change the pasted image file location, but the file path still under hexo source dir, how can I change the location into my custom path not in hexo source dir

**Comment by pirtleshell** [comment]
hexo is setup to only know about and serve files in it's source directory. the files you upload are expected to be used a served to the client, so the files are saved to that directory.

i'm unclear on the use case that would require your files to be somewhere else. the uploaded image path setting is relative to Hexo's source directory. would you explain why one might want to upload the images to a location outside of this source? if good arguments are made, we could add an additional setting for overriding the source directory when uploading images.

if you're interested in taking a stab at this, you'd want to add a new setting (see [here](https://github.com/jaredly/hexo-admin/blob/master/client/settings.js) for examples), & then modify the [`images/upload` api endpoint](https://github.com/jaredly/hexo-admin/blob/master/api.js#L337) to use the setting value in place of `hexo.source_dir` if it is set.
