### ISSUE TITLE
why backslash ?

### ISSUE THREAD

**Issue by cloisonne** [jaredly/hexo-admin#160]
like this：

![upload successful](\\images\pasted-2.png\)

![upload successful](\\images\pasted-3.png\)

![upload successful](\\images\pasted-4.png\)

**Comment by pirtleshell** [comment]
excellent point!

the `images/upload` endpoint returns the filepath, and your server instance is likely running on a Windows machine which uses the backslash for paths. we should probably check and replace them with forward slashes before returning the value.
