### ISSUE TITLE
two categories generated in post edit page

### ISSUE THREAD

**Issue by bejondshao** [jaredly/hexo-admin#164]
I add 
```
metadata:
    categories: Default
```

in the _config.yml, aim to set default category for the new post.

When I create new post, and open setting for the post, I can see two "categories" in the dialog.

**Comment by pirtleshell** [comment]
Hi @bejondshao, "Categories" is a built-in front-matter item of hexo, so metadata won't play nice with it. Set the default category in your config with
```
default_category: Default
```

**Comment by bejondshao** [comment]
Hi pirtleshell, I met the issue that default_category doesn't work for me. Issue is [here](https://github.com/hexojs/hexo/issues/2912).  So I try to use metadata to work for me. And it works! But the new issue comes when rendering in /admin/*. :joy:
