### ISSUE TITLE
It will be great if it supports markdown toolbar

### ISSUE THREAD

**Issue by bejondshao** [jaredly/hexo-admin#166]
Thanks to the plugin and makes me edit posts without other editors. If it supports markdown tags toolbar would be perfect. Nearly 1K starts, I believe a lot of people want this feature. Thank you.

**Comment by melvinthoabala** [comment]
This will be a cool feature 🚀

**Comment by fadehelix** [comment]
I think that this is related to #88 ;) 
IMHO the main blocker for this feature is a deprecated React version and workflow (would be better to use Webpack instead of Browserify). I am going to do this, but it is not as easy I want and would be great if someone else could help ;)

**Comment by pirtleshell** [comment]
thanks for the suggestion. closing as duplicate of #88
