### ISSUE TITLE
Doesn't create new post

### ISSUE THREAD

**Issue by yarax** [jaredly/hexo-admin#18]
When creating new post nothing happens (no xhr requests and new files in source)
Also there is nothing in console

**Comment by jaredly** [comment]
Hmmm I can't reproduce, using a freshly installed 0.3.0. Is this still an issue?
Also, what node version & OS?

**Comment by jaredly** [comment]
Hmmm I can't reproduce, using a freshly installed 0.3.0. Is this still an issue?
Also, what node version & OS?

**Comment by omero72** [comment]
What yarax says happens in my computer, too. My system info:
OSX 10.7.4 & node-v0.10.21 (node binary date Oct19, 2013)
I updated node.js to v0.12.0 (node binary date Feb6, 2015) still the same problem.
I've added those 4 lines to _config.yml:

 admin:
  username: gomez
  password_hash: be121740bf988b2225a313fa1f107ca1
 secret: a secret something

And, visiting the /admin doesn't ask for a password!

**Comment by yarax** [comment]
I guess, that npm version is still old and hasn't admin protection feature
And I will see what's the problem with new posts

**Comment by omero72** [comment]
As far as the npm on my system's concerned, it's the latest version, too : npm -v --> 2.5.1 because it was automatically updated under the node.js package.
But just one guess: I have installed the hexo-admin using the uptdated version of npm and so I uninstalled both hexo and hexo-admin and tried installing again and I've run into a build error, related to something like node-gyp. So I uninstalled node.js and npm and will reinstall them for good measure. And while I'm at it, I will compile node.js & npm from source and try the hexa again. It might take a while, afterwards I'll post back.

**Comment by yarax** [comment]
I mean the version of hexo-admin into the npm repository. It should be published there additionally. And as I understand, password protection is still a testing feature. But untill it hasn't published you can do `git clone https://github.com/jaredly/hexo-admin.git hexo-admin-plugin` inside the hexo directory.
It whould works

**Comment by omero72** [comment]
Oh yes you seem to be correct. After I downloaded those 2 git repos into the hexo dir, it became ok! Thanks.

**Comment by sangbumwoo** [comment]
"Doesn't create new post" problem is cleared or not ?
I'm still can not create new post from admin.

**Comment by jaredly** [comment]
What is your version of `hexo`, and of `hexo-admin`?

**Comment by sangbumwoo** [comment]
Thanks for reply.

I have tested to create post again. 
After I typed title I have clicked check button. Nothing happen. 
When I press enter, it works. 
I think the UI can make confuse users. It is better to go enter mode when user click check button.

Now I tried to delete post, but I can not find delete button. 
Am I missing something ?

**Comment by jaredly** [comment]
Yeah, there's no post deletion via the UI at the moment -- you just rm the file. I haven't gotten around to adding a button for it, and I'd rather stay on the safe side -- given that we're dealing with files, deletion is irreversible. Unless we just moved the files to a `deleted` folder, which would make a lot of sense.

**Comment by corbt** [comment]
Can reproduce @sangbumwoo (and it's probably the problem that everyone else is running into here). One guy on our team could *not* create a new post, and it worked for everyone else. Turns out he was the only person using the checkmark instead of the "enter" key!

**Comment by jaredly** [comment]
sorry this sat unfixed for so long! it was a really simple change too. justed published hexo-admin@1.1.2 and it should solve this for you :)
