### ISSUE TITLE
Support adding static pages

### ISSUE THREAD

**Issue by jaredly** [jaredly/hexo-admin#2]
This would be good to implement

**Comment by nkoehring** [comment]
+1

I see pages in the menu but I need to create/delete them via console at the moment. Is the implementation planned?

**Comment by jaredly** [comment]
not actively :) I don't tend to create/delete static pages too often

**Comment by jaredly** [comment]
Useful starting points:

Server:
[This](https://github.com/jaredly/hexo-admin/blob/master/api.js#L128) is the current endpoint for getting/updating pages link. You can see below it the `posts/new` endpoint -- we'll need a `pages/new` endpoint that will just take a `title`, and then return the page model. [Here's the call](https://github.com/jaredly/hexo-admin/blob/8b16380c21fe49b4b5ef997b4a8b04e979e4ee12/client/api/rest.js#L47) on the front-end that will use the endpoint.

Frontend:
The frontend is mostly implemented for it (see this [commented out line](https://github.com/jaredly/hexo-admin/blob/8b16380c21fe49b4b5ef997b4a8b04e979e4ee12/client/pages.js#L51)) -- I think you'll only need to uncomment that line.

**Comment by jaredly** [comment]
Delete isn't even supported for posts yet :D but it also shouldn't be too hard. If someone wants to put together the backend endpoint, I can put a button somewhere.

**Comment by yfsoftcom** [comment]
i fix the 'new page' feature
plz accept my pr:  
[https://github.com/jaredly/hexo-admin/pull/117/commits/32dea78eeae09cd9aa0235c3d33d77b6094ceb87](https://github.com/jaredly/hexo-admin/pull/117/commits/32dea78eeae09cd9aa0235c3d33d77b6094ceb87)

**Comment by PirtleShell** [comment]
Added and merged in #120
