### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by Meditly** [jaredly/hexo-admin#234]
I have always been a white screen, only loaded the title but no content.
我是一直白色的屏幕，只加载了标题但是没有内容。

**Comment by tonywdy** [comment]
你看看www文件夹，可能是bundle.js之类的文件错误

**Comment by PangHuwo** [comment]
> I have always been a white screen, only loaded the title but no content. 我是一直白色的屏幕，只加载了标题但是没有内容。

这是因为，存在一屏的空白页，你滑动滚动条即可

**Comment by Meditly** [comment]
Thanks!
