### ISSUE TITLE
Support for Hexo 3.x?

### ISSUE THREAD

**Issue by iamgyz** [jaredly/hexo-admin#25]
Hello Jaredly!
I really appreciate of your amazing work on Hexo.
I am wondering if hexo-admin can work fine with Hexo 3.x

Thanks!

**Comment by jaredly** [comment]
It doesn't currently, and I don't at the moment have the bandwidth to upgrade it :/ there is a pull request out, but it needs some revision https://github.com/jaredly/hexo-admin/pull/20

**Comment by iamgyz** [comment]
Oh! I see.

Thanks for your reply!
