### ISSUE TITLE
README for v1.1.1

### ISSUE THREAD

**Issue by wzpan** [jaredly/hexo-admin#29]
I want to install hexo-admin v1.1.1 for Hexo 3. According to README:

```sh
$ npm install --save hexo-admin-plugin
```

I found it only install hexo-admin-plugin@0.1.2. Then I searched the npm packages and found another repo called `hexo-admin` that should be the one to install.

However, even though I installed it via the following command:

``` sh
$ npm install --save hexo-admin
```

, it will still complaints that some modules sort of `depd`, `debug`, `bytes`, `http-errors`, `icon-lite`... are missing as I type `hexo server -d`.

So could you update the README and help me install v1.1.1? Thanks.

``` sh
hexo: 3.1.1
os: Darwin 14.5.0 darwin x64
http_parser: 2.3
node: 0.12.4
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by wzpan** [comment]
Maybe the `dependencies` part of package.json file should be modified a little bit:

```json
"dependencies": {
    "MD5": "^1.2.1",
    "bytes": "^2.1.0",
    "content-type": "^1.0.1",
    "debug": "^2.2.0",
    "depd": "^1.1.0",
    "body-parser": "^1.5.0",
    "browserify": "^11.2.0",
    "connect-auth": "^0.6.1",
    "cookie-parser": "^1.3.4",
    "express-session": "^1.10.3",
    "extend": "^3.0.0",
    "hexo-front-matter": "^0.2.2",
    "hexo-fs": "^0.1.3",
    "hexo-util": "^0.1.6",
    "less": "^2.5.1",
    "moment": "^2.7.0",
    "qs": "^5.1.0",
    "serve-static": "^1.4.0",
    "type-is": "^1.6.9",
    "http-errors": "^1.3.1",
    "iconv-lite": "^0.4.12",
    "on-finished": "^2.3.0",
    "raw-body": "^2.1.3",
    "serve-static": "^1.10.0"
  },
```

Now it stops complaining missing modules. But after I enter the admin page, I can only see a blank page.

**Comment by EvanCarroll** [comment]
hexo-admin. not hexo-admin-plugin.
