### ISSUE TITLE
hexo generate with this plugin

### ISSUE THREAD

**Issue by Pana** [jaredly/hexo-admin#31]
I use hexo generate to get my blog static files, can i use this plugin in this way

**Comment by jaredly** [comment]
Yup, that's how I do it.

**Comment by lsmoura** [comment]
Is it possible to create a "Generate" button somewhere in the interface? Can we call ```hexo generate``` this way?

**Comment by TivonJJ** [comment]
yeah ! It's useful，I need too，Or every time you need to log in ssh and generate.....

**Comment by adrianveracom** [comment]
@lsmoura @TivonJJ Just added it here https://github.com/jaredly/hexo-admin/pull/42

**Comment by haobingwang** [comment]
I use generate command by `deployCommand`. 
@adrianveracom you drop the PR?
