### ISSUE TITLE
Adding deploy option in admin dashboard

### ISSUE THREAD

**Issue by tsturzl** [jaredly/hexo-admin#36]
I host my blog as static pages on github. I use the admin dashboard mainly for the markdown editor and the ease of use. What I'd really like to see is something to generate and deploy, so I can publish posts. Maybe even have a feature to generate and deploy when an article is published, though it would make most sense to have a "Publish" button then.

I'd be interested in making a PR request. I don't think this would be too difficult to implement. Does anyone else feel like this would be an attractive feature?

**Comment by jaredly** [comment]
See https://github.com/jaredly/hexo-admin/issues/9
I haven't published it to npm yet though
