### ISSUE TITLE
it doesn't work in live server

### ISSUE THREAD

**Issue by boring2** [jaredly/hexo-admin#37]
When I test the module in localhost:4000/admin, it works normal.But when I deploy to github and open the url http://blog.boring.ren/admin find it doesn't work.The error is 404.

**Comment by jaredly** [comment]
github pages are static (no server, just html/css/js files), so hexo-admin wouldn't make sense there.
If you have hexo deployed *not* in static mode, then hexo admin works fine

**Comment by nekonejo** [comment]
hi, con I deploy hexo in not static mode? can you share a step by step guide? I'm completely noob

**Comment by SouthernYard** [comment]
@jaredly Hi jareyly, how to deploy hexo as a **dynamic** mode? I also encounter this issue recently.
I deploy hexo blog on my own server. Before setting the https server, the "/admin" page can navigate, but now it is forbidden. In my https server configuration, the root path is "/home/hexo/public". And then the  "/admin" is blocked. How can I access the "/admin" page again.
In other words, if I deploy my application as the dynamic mode, does this issue can be solved?

Thanks,
Shawn

**Comment by declan-haojin** [comment]
@SouthernYard So do I. I encounter the same problem with you. I use hexo-admin in my non-static hosting server. All is fine when running localhost:4000, but the /admin page is 404 when visited by /public folder. Could anyone give a help?
