### ISSUE TITLE
MD5 causing warning

### ISSUE THREAD

**Issue by EvanCarroll** [jaredly/hexo-admin#39]
npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on

**Comment by EvanCarroll** [comment]
Already fixed here https://github.com/lsmoura/hexo-admin please pull!

**Comment by jaredly** [comment]
Could you make a pull-request with just the dependency change, and without the index.html change? (while some editors might not like it, it is [completely valid html](http://stackoverflow.com/a/25749523/290784))

**Comment by EvanCarroll** [comment]
Perhaps valid, but even on that very page it breaks in IE9. Is that advisable to make the trivial point that what you're doing technically should be permitted? It makes sense from Google's POV, "let's break IE9 because they fucked this up." But, that's the wrong attitude. Anyway, to answer your question no. It's not my fork.

**Comment by jaredly** [comment]
via #40
