### ISSUE TITLE
remove post

### ISSUE THREAD

**Issue by jaredly** [jaredly/hexo-admin#4]
I'm thinking I'll move them to a `_discarded` directory, and let you restore them, or clean it out.

**Comment by wodCZ** [comment]
+1

**Comment by adrianveracom** [comment]
+1 to this.

**Comment by EvanCarroll** [comment]
+1

**Comment by ThatTobMate** [comment]
+1

**Comment by dbYoung** [comment]
+!

**Comment by jaredly** [comment]
If someone wants to contribute a PR, that'd be cool. the backend's actually already in place -- you just call `/api/posts/{post id}/remove` and it will move the file over. It's not tested at all, but it'll probably do fine. all we need is a button somewhere (you can put a button right next to [publish](https://github.com/jaredly/hexo-admin/blob/master/client/editor.js#L48) if you want).
I'm happy to give feedback/additional coaching if desired.

**Comment by dalibormesaric** [comment]
I added this functionality, but let's resolve https://github.com/jaredly/hexo-admin/pull/54 first, since it is a dependency for me.

Also, I will need someone to style this :)

**Comment by Captain1** [comment]
+1 would be nice to have this feature! draft zone and trash box kind of thing.

**Comment by kousha-icracked** [comment]
When is this feature expected?

**Comment by PirtleShell** [comment]
The feature is here.
