### ISSUE TITLE
Can the plugin take effect on server?

### ISSUE THREAD

**Issue by iancui** [jaredly/hexo-admin#43]
At local , http://localhost:4000/admin/   can take effect. but ,at my website(xxxx.com/admin) can't take effect.Is it my wrong? Can you give me some advice?

**Comment by jaredly** [comment]
If you host your site using github (or some other static site host like surge.sh), then `hexo-admin` won't work. If you use a normal host (like bluehost or digitalocean, etc) and you use `hexo-server` there, then `hexo-admin` will work, but you should password-protect it.

**Comment by benmarten** [comment]
I wrote a blog post about how to deploy hexo with hero-admin to heroku or dokku: https://blog.benmarten.me/2015/12/23/HOWTO-Run-Hexo-Hexo-Admin-on-Heroku-or-Dokku/
This should solve your issue ;)

**Comment by iancui** [comment]
@benmarten The site can't visit.
@jaredly Thank you for your advice
