### ISSUE TITLE
Add cookie secret how-to on Readme.md

### ISSUE THREAD

**Issue by baram204** [jaredly/hexo-admin#48]
I want to know how can i use "secret" for cookie protection

So, Would you mind if i asking you to write about "secret" more specifically?

**Comment by jaredly** [comment]
`secret` just needs to be a random string of characters that can't be guessed. you can use any of the longer strings generated by http://randomkeygen.com/ , for example (just grab one from under "CodeIgniter keys")

**Comment by PirtleShell** [comment]
Hexo admin now generates the `admin` section for you. #109
