### ISSUE TITLE
[feature]show line numbers & can setting CRLF or LF

### ISSUE THREAD

**Issue by myoss** [jaredly/hexo-admin#50]

**Comment by PirtleShell** [comment]
Line numbers can pretty trivially be added to the editor by going to `hexo-admin/lib/code-mirror.js` and insert
```json
lineNumbers: true
```
into the the CodeMirror configurations. You can directly insert this into [line 25](https://github.com/jaredly/hexo-admin/blob/430d07f4d3c0329a762a2bbb0735887a67c125b4/client/code-mirror.js#L25) and then `gulp build` in the `hexo-admin` root.

[Here's the link to the option in the CodeMirror docs.](https://codemirror.net/doc/manual.html#option_lineNumbers)
