### ISSUE TITLE
Choice of MD5 for password hashing

### ISSUE THREAD

**Issue by ronnieoverby** [jaredly/hexo-admin#51]
Why was MD5 chosen? 
MD5 should never be used in a security context: https://www.google.com/search?q=md5%20security%20vulnerability

**Comment by ronnieoverby** [comment]
Just wanted to relay a more specific resource on the topic: https://en.wikipedia.org/wiki/MD5#Security

**Comment by jaredly** [comment]
oh yeah, that was pure oversight. I don't use hexo-admin in a hosted
(+password protected) capacity, so haven't watched that code quite as
closely.
I just published version 2.0.0 which uses bcrypt instead of md5
