### ISSUE TITLE
Cannot GET /admin after entering password variable

### ISSUE THREAD

**Issue by wcorbett36** [jaredly/hexo-admin#52]
Hi there,  

I entered the password variable to the _config.yml but after reboot /admin returns cannot GET admin  

Please advise, works with the .yml variables removed.

Thanks,

**Comment by jaredly** [comment]
Is this with version 2.0.0? I published a fix a few weeks ago for the admin login issue

**Comment by v123582** [comment]
@jaredly @wcorbett36 what is your root url?

i have same problem because i used the custom root url.
plz check this pr: https://github.com/jaredly/hexo-admin/pull/57
