### ISSUE TITLE
edit posts, split is not 50%

### ISSUE THREAD

**Issue by myoss** [jaredly/hexo-admin#56]
![20160314152344](https://cloud.githubusercontent.com/assets/6986459/13737488/c17d7914-e9f8-11e5-8016-4c7100708035.png)

**Comment by jaredly** [comment]
try installing v2.0.1, and let me know if that doesn't fix it

**Comment by myoss** [comment]
not ok ...

test 1:
![20160315182358](https://cloud.githubusercontent.com/assets/6986459/13774698/47d3f6a4-eadb-11e5-81f6-8df1ad113f96.png)


test 2:
![20160315182424](https://cloud.githubusercontent.com/assets/6986459/13774701/4a77d89e-eadb-11e5-9ba5-d87efa408519.png)
