### ISSUE TITLE
change display_name?

### ISSUE THREAD

**Issue by calidion** [jaredly/hexo-admin#62]
is it possible to change display_name or set a default display_name from hexo-admin?

**Comment by jaredly** [comment]
hmmm not sure what you mean by that. could you explain?

**Comment by calidion** [comment]
@jaredly 
the hexo-admin now supports edition for tags, categories and creation time, but not the author name.
I have to manually change the author name for every article.
So it would be nice to have the ability to set a default author name and can change it for articales respectively.
thanks.

**Comment by PirtleShell** [comment]
`hexo-admin` now supports editing author names, so I'm closing this. Feel free to reopen if something else was meant by 'display_name'.
