### ISSUE TITLE
"New Post" cannot be created

### ISSUE THREAD

**Issue by jiji262** [jaredly/hexo-admin#65]
Reproduce it:
1) Click the "New Post" button
2) input title
3) click the "ok" icon

The following error shows up:

> Unhandled rejection WarehouseError: ID `source/_drafts/first-page.md` has been used
>     at new WarehouseError (d:\node\myhexo\node_modules\warehouse\lib\error.js:17:11)
>     at Model._insertOne (d:\node\myhexo\node_modules\warehouse\lib\model.js:185:27)
>     at d:\node\myhexo\node_modules\warehouse\lib\model.js:214:17
>     at tryCatcher (d:\node\myhexo\node_modules\bluebird\js\release\util.js:16:23)
>     at d:\node\myhexo\node_modules\bluebird\js\release\using.js:184:26
>     at tryCatcher (d:\node\myhexo\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:502:31)
>     at Promise._settlePromise (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:559:18)
>     at Promise._settlePromise0 (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:604:10)
>     at Promise._settlePromises (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:683:18)
>     at Promise._fulfill (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:628:18)
>     at PromiseArray._resolve (d:\node\myhexo\node_modules\bluebird\js\release\promise_array.js:125:19)
>     at PromiseArray._promiseFulfilled (d:\node\myhexo\node_modules\bluebird\js\release\promise_array.js:143:14)
>     at Promise._settlePromise (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:564:26)
>     at Promise._settlePromise0 (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:604:10)
>     at Promise._settlePromises (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:683:18)
>     at Async._drainQueue (d:\node\myhexo\node_modules\bluebird\js\release\async.js:138:16)
>     at Async._drainQueues (d:\node\myhexo\node_modules\bluebird\js\release\async.js:148:10)
>     at Immediate.Async.drainQueues [as _onImmediate](d:nodemyhexonode_modulesbluebirdjsreleaseasync.js:17:14)
>     at processImmediate [as _immediateCallback](timers.js:383:17)
> 
> Unhandled rejection TypeError: Cannot read property 'source' of undefined
>     at addIsDraft (d:\node\myhexo\node_modules\hexo-admin\api.js:11:24)
>     at d:\node\myhexo\node_modules\hexo-admin\api.js:187:18
>     at tryCatcher (d:\node\myhexo\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:502:31)
>     at Promise._settlePromise (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:559:18)
>     at Promise._settlePromise0 (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:604:10)
>     at Promise._settlePromises (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:683:18)
>     at Promise._fulfill (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:628:18)
>     at Promise._settlePromise (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:572:21)
>     at Promise._settlePromise0 (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:604:10)
>     at Promise._settlePromises (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:683:18)
>     at Promise._fulfill (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:628:18)
>     at Promise._resolveCallback (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:445:14)
>     at Promise._settlePromiseFromHandler (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:514:17)
>     at Promise._settlePromise (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:559:18)
>     at Promise._settlePromise0 (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:604:10)
>     at Promise._settlePromises (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:683:18)
>     at Promise._fulfill (d:\node\myhexo\node_modules\bluebird\js\release\promise.js:628:18)
>     at MappingPromiseArray.PromiseArray._resolve (d:\node\myhexo\node_modules\bluebird\js\release\promise_array.js:125:19)
>     at MappingPromiseArray._promiseFulfilled (d:\node\myhexo\node_modules\bluebird\js\release\map.js:97:18)
>     at MappingPromiseArray.PromiseArray._iterate (d:\node\myhexo\node_modules\bluebird\js\release\promise_array.js:113:31)
>     at MappingPromiseArray.init (d:\node\myhexo\node_modules\bluebird\js\release\promise_array.js:77:10)

My system is windows8.1, and node version is V4.4.1

**Comment by giacomocerquone** [comment]
I'm experiencing a similar problem. I don't know what version of Hexo you're running but with mine (3.2.0 that's the last one) I receive an error (not identical to yours) even if I create a new post like this: `hexo new asdasdasd`.
Try to give that command and see if it generates error. If so you can solve this problem easily filling the front-matter (things like tags, categories etc. of the posts).

My error seems to be an hexo bug.

**Comment by PirtleShell** [comment]
Is this still a problem Windows users are experiencing?

**Comment by yfsoftcom** [comment]
I fix the 'new page' on mac and linux~ 
see the commit:
[https://github.com/jaredly/hexo-admin/pull/117/commits/32dea78eeae09cd9aa0235c3d33d77b6094ceb87](https://github.com/jaredly/hexo-admin/pull/117/commits/32dea78eeae09cd9aa0235c3d33d77b6094ceb87)
