### ISSUE TITLE
Error: Config value "admin.deployCommand" not found

### ISSUE THREAD

**Issue by panw3i** [jaredly/hexo-admin#67]
i use ubuntu14.04 and reference  this blog https://www.digitalocean.com/community/tutorials/how-to-create-a-blog-with-hexo-on-ubuntu-14-04

**Comment by jaredly** [comment]
In what context do you encounter this error?

**Comment by vladpurga** [comment]
https://github.com/jaredly/hexo-admin/issues/70

**Comment by PirtleShell** [comment]
Closing as duplicate.
