### ISSUE TITLE
Cannot publish/unpublish post on Windows.Source is undefined

### ISSUE THREAD

**Issue by MishaTyupa** [jaredly/hexo-admin#68]
When I try to publish/unpublish post I got error "source is undefined" and after reloading the page a post will be updated... .It seems like it was a similar issue with creating new post and replacing slashes "var post = hexo.model('Post').findOne({source: source.replace(/\/g, '\/')})" resolve this issue,but still you have the same issue with publish/unpublish/remove posts.
Can you figure it out,please?

**Comment by jaredly** [comment]
Hmm yeah that might be the same issue. Do you want to try implementing that fix and let me know how it goes? I don't have a windows machine to test with.
