### ISSUE TITLE
What is admin.deployCommand?

### ISSUE THREAD

**Issue by JaxXu** [jaredly/hexo-admin#70]
What is admin.deployCommand?

**Comment by grinka** [comment]
![image](https://cloud.githubusercontent.com/assets/109873/15278806/9f1a9afe-1aeb-11e6-8ce1-4593b9bdee23.png)

I have the problem with `admin.deployCommand` too.

**Comment by grinka** [comment]
I've found the like with deployCommand here: https://github.com/jaredly/hexo-admin/blob/8312967c7f707418dbb6ae5116e03292862d9dc4/api.js

``` js
use('deploy', function(req, res, next) {
    if (req.method !== 'POST') return next()
    if (!hexo.config.admin || !hexo.config.admin.deployCommand) {
      return res.done({error: 'Config value "admin.deployCommand" not found'});
    }
    try {
      deploy(hexo.config.admin.deployCommand, req.body.message, function(err, result) {
        console.log('res', err, result);
        if (err) {
          return res.done({error: err.message || err})
        }
        res.done(result);
      });
    } catch (e) {
      console.log('EEE', e);
      res.done({error: e.message})
    }
  });
```

I tried to fill the `admin` section with different values of this parameter - nothing seems to work. Unfortunately.

**Comment by vladpurga** [comment]
```$ touch hexo-deploy.sh; chmod a+x hexo-deploy.sh```
in project dir with such 2 lines for example or any custom code 

```shell
#!/usr/bin/env sh
hexo deploy
```
and add 2 lines in _config.yml:
```yaml
admin:
  deployCommand: './hexo-deploy.sh'
```

* https://github.com/vladpurga/hexo-admin-deploy-command

**Comment by PirtleShell** [comment]
This appears sufficiently answered thanks to @vladpurga. The deploy command is any command you'd like run on the terminal. Placing many commands in a bash script or batch file is a great way to do it.

Be aware that Windows does not use hashbangs (telling how to execute the file with the first line of a file, the `#!/usr/bin/env sh` in the example above). Thus, you'll need to play with what command will execute properly, perhaps by [using a batch file](https://en.wikipedia.org/wiki/Batch_file) or prefacing your hexo command with `node.exe` or some other Windows-recognized executable command.
