### ISSUE TITLE
Unhandled 'error' event, Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by jemyzhang** [jaredly/hexo-admin#74]
Error happened while publish a new post, or just click to edit the tag.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)

```

**Comment by PirtleShell** [comment]
Sorry we never got to you. It looks like you lack the reading permission on your source directory. You can change this with the command:
```
chmod +r source/
```

Please reopen this if you still have problems.
