### ISSUE TITLE
at github.io service not open /admin

### ISSUE THREAD

**Issue by zengcanxiang** [jaredly/hexo-admin#76]
at the local ,config admin,is ok open.
but, submit the githubio service ,not open admin.
package.json contain  "dependencies":  "hexo-admin": "^2.0.1".
I was very confused.Ask you how I should configure github.io.
github.io mapping to domain name.

**Comment by levingit** [comment]
me too

**Comment by jaredly** [comment]
github.io is a **static** host, which means that `hexo-admin` won't work when deployed there.
Hexo admin relies on having a server running that can modify your files, etc.
Github's hosting service doesn't allow running a custom node server, so only the static (generated) version of your blog, without any dynamic parts such as hexo-admin, will work there.
If you want, you could deploy hexo to something like heroku and run the hexo server, which would support using hexo-admin

**Comment by zengcanxiang** [comment]
@jaredly thanks.I have been very confused.
