### ISSUE TITLE
Error in Editor

### ISSUE THREAD

**Issue by Svtter** [jaredly/hexo-admin#80]
![image](https://cloud.githubusercontent.com/assets/5856931/17462298/3a3759ec-5cdb-11e6-84fe-1b50aa8e9aa1.png)

The `# vi /etc/main.rc` should not be `header`.

**Comment by PirtleShell** [comment]
This would be an error in [CodeMirror](https://github.com/codemirror/codemirror). The codeblock will still render properly on the frontend, so although it isn't ideal, I don't imagine that it will be resolved quickly as it's purely an aesthetic problem.

**Comment by jaredly** [comment]
@PirtleShell is this probably fixes w/ the codemirror upgrade?

**Comment by PirtleShell** [comment]
Yup! This has been fixed.

![](https://cloud.githubusercontent.com/assets/14897503/21108931/8a31aeae-c05c-11e6-9950-22d3cd56fc48.png)
