### ISSUE TITLE
Bug: All my articles show left are incomplete.

### ISSUE THREAD

**Issue by xnervwang** [jaredly/hexo-admin#81]
All my articles show left are incomplete. The front part is missing. Is is right?

like this:
![_20160821180837](https://cloud.githubusercontent.com/assets/4509104/17836606/b910f986-67ca-11e6-90a1-65e4f6622ac2.png)

**Comment by PirtleShell** [comment]
Hi @xnervwang do you still have this error when editing your posts?

**Comment by PirtleShell** [comment]
Closing this for now. Feel free to open reopen the issue if you still have problems
