### ISSUE TITLE
Scroll-sync

### ISSUE THREAD

**Issue by rahil471** [jaredly/hexo-admin#89]
Hey I have built my own markdown editor, but I'm struggling with syncing the scroll of markdown and it's preview, can guide me how you did it or point me out to the code in the repo. Would be great help.

Thanks, in advance.

**Comment by jaredly** [comment]
I'm just doing percentage-based scrolling; https://github.com/jaredly/hexo-admin/blob/master/client/code-mirror.js#L32
not super sophisticated, but generally gets the job done

**Comment by rahil471** [comment]
Thanks for the info, that helps!
