### ISSUE TITLE
Hexo Deploy

### ISSUE THREAD

**Issue by abstracthat** [jaredly/hexo-admin#9]
The Publish button is only local of course since we are running the Hexo server. Maybe if you had a settings file we could specify if we want to keep functionality local only as you have it, or also call `hexo deploy -g` or some other shell command for custom deployments.

**Comment by wodCZ** [comment]
Also hexo generate would be great

**Comment by bobchennan** [comment]
I have implemented a simple deploy page. It calls a script specified in the yml configuration and takes the first parameter as commit log.

Added a pull request.

Also support uploading pictures would be great

**Comment by jaredly** [comment]
You can copy+paste pictures into the editor already. It would probably be good to have a button you can click to browse for an image though
