### ISSUE TITLE
Is there a way to use hexo-admin in production mode?

### ISSUE THREAD

**Issue by simonbruneaud** [jaredly/hexo-admin#90]
Hi, I noticed that only static files are pushed to heroku.

Is there a way to use admin in production mode?
That involve to push dynamic server hexo to heroku.. And I don't know how to do this

**Comment by jaredly** [comment]
There are two ways to deploy hexo - as a static site, and as a dynamic site. `hexo-deployer-hero` just deploys the site statically, as you've noticed.
check out #49 for more info
