### ISSUE TITLE
code preview problem

### ISSUE THREAD

**Issue by xbotao** [jaredly/hexo-admin#95]
![qq 20161231183400](https://cloud.githubusercontent.com/assets/6964173/21577083/afa484e6-cf88-11e6-88ce-8b1dad60ad63.jpg)

I use windows and firefox.The code preview has some blank lines at the end.How to deal it.

**Comment by PirtleShell** [comment]
What is the markdown that produced the bad preview? Is it like this when you first go to edit the page, or is this what is visible as you're typing?

Hexo admin uses [marked](https://github.com/chjj/marked) to live render a preview, but the html from your hexo-renderer is what you see when you go to edit a post and no changes have been made.

If it appears this way when you first arrive to the page, see if it gets pretty after you start editing.

**Comment by xbotao** [comment]
Both of these.
![qq 20170101125930](https://cloud.githubusercontent.com/assets/6964173/21580249/500a152e-d022-11e6-8632-3f30f72e4aa3.jpg)
![qq 20170101125959](https://cloud.githubusercontent.com/assets/6964173/21580250/500c157c-d022-11e6-8839-14b9f702fe7f.jpg)

The blank lines between the codes when I typeing it.But it apper at the end when preview the code.
![qq 20170101130453](https://cloud.githubusercontent.com/assets/6964173/21580259/ee33662e-d022-11e6-93c7-81cc031b6ba9.jpg)

**Comment by PirtleShell** [comment]
I see. This only happens when you first view the page, as live-preview (while you're editing and having made changes) code tags aren't run through a syntax highlighter.

To fix this, go to hexo-admin and add the following css to `www/css/screen.css`:
```css
pre .line {
  height: 20px
}

**Comment by xbotao** [comment]
It works.
Thanks!

**Comment by xbotao** [comment]
Please fix this problem on the new version, @PirtleShell .
Thanks!
