### ISSUE TITLE
delete post

### ISSUE THREAD

**Issue by lamaaa** [jaredly/hexo-admin#96]
Hello,I want to delete my post,but I can't find the post in the ./source/_posts/.So, how should I do?

**Comment by xbotao** [comment]
Have you published? If not, find the post in './source/_drafts/'

**Comment by xbotao** [comment]
You could delete your post quickly in editor.
![qq 20170101130932](https://cloud.githubusercontent.com/assets/6964173/21580263/93bfbd22-d023-11e6-8e29-e2f275f7ed39.jpg)

**Comment by lamaaa** [comment]
@xbotao it's ok! thank you.
