### ISSUE TITLE
Scrolling layout of admin does not work in Firefox

### ISSUE THREAD

**Issue by xbotao** [jaredly/hexo-admin#98]
If there are many posts and the posts is short, click the early post(at the end of the list), can not see the preview friendly.So I sugguest **the list** and the **preview area** roll lonely.
like this:

![qq 20170101172713](https://cloud.githubusercontent.com/assets/6964173/21580708/a029b742-d047-11e6-8123-3595f8477ad6.jpg)

**Comment by PirtleShell** [comment]
If I'm understanding correctly, the scrolling of your list of posts affects the scrolling of the preview? So when you try to look at posts on the bottom, the scrolling makes it so you can't see the top of the preview?

If that is what you mean, I'm unable to reproduce the issue. If it's not what you mean, could you try and explain the problem again? The list scrolling is independent of the preview area scrolling.

**Comment by xbotao** [comment]
Yes.The scrolling of your list of posts affects the scrolling of the preview and I can't see the top of the preview when  I try to look at  posts on the bottom.

发自我的 iPhone

**Comment by xbotao** [comment]
I try it on the ubuntu16.04 64bit, the issue appers the same with the windows 10.
follow 
```
1. Setup hexo & create a blog

npm install -g hexo
cd ~/
hexo init my-blog
cd my-blog
npm install

2. Install the admin & start things up

npm install --save hexo-admin
hexo server -d
open http://localhost:4000/admin/
```

**Comment by xbotao** [comment]
Are you have some idea about this?

**Comment by PirtleShell** [comment]
Sorry, I haven't been able to reproduce this error, and in the code the scrolling does not appear to be linked. When viewing a post at the bottom of a long posts list, the preview begins at the top of the post. scrolling around the post list does not change the scrolling of the preview.

I can't think of what would be causing this for you...

**Comment by xbotao** [comment]
![qq 20170104091155](https://cloud.githubusercontent.com/assets/6964173/21628870/e35dcba8-d25d-11e6-94f5-b6e6ea6146f9.jpg)

There is not have scrollerbar of the list box or preview box. Just a page scollerbar, So……
Is this controled by the js? or the css ?

Could I get the problem by Developer Tools? what element should I watch?

**Comment by xbotao** [comment]
Could you given a screenshot about your hexo-admin?

**Comment by PirtleShell** [comment]
Weird. I have a scroll bar.

![image](https://cloud.githubusercontent.com/assets/14897503/21629034/1d777cb8-d1ea-11e6-87cb-4594078b9161.png)

What browser are you using? Inspect the posts list. It should have the class `.posts_list` which has `overflow: auto` which on most browsers is equialent to `scroll`.

**Comment by xbotao** [comment]
My browser is Firefox 50.1.0. 
I test it on IE, Firefox and chorme a moment ago.
Just chorme is OK.

But in Firefox browser, the `.posts_list` has the `overflow: auto`.
```
.posts_list {
    background-color: #F7FAFF;
    list-style: none;
    padding: 0;
    margin: 0;
    width: 400px;
    overflow: auto;
}
```

**Comment by xbotao** [comment]
I test if on the `ubuntu 16.04, Firefox@50.1.0`, the same issue apeared.

**Comment by PirtleShell** [comment]
Well that _is_ a bug now isn't it? :smile:
It looks like `.app_main` needs something to limit its height. Probably some difference in how chrome handles flexboxes.

**Comment by xbotao** [comment]
I think you are right.

**Comment by PirtleShell** [comment]
Also, in Firefox, the height of `.app_main` affects the scrolling functionality of the editor. For now, use Chrome for the best experience. If you're up for it, try and play with the CSS to see if you can get a similar experience in Firefox as Chrome. I'll play around with it tomorrow. It looks like giving `.app_main` the right `max-height` will fix the problem, but there's probably a more root cause to the problem.

**Comment by xbotao** [comment]
The follow HTML is ok in IE, Firefox and chrome.

```
<!doctype html>
<html>
<head>
    <meta charset="utf-8" /> 
    <title>Lazyboy Editor</title>
    <style>
    html, body{
        margin: 0;
        padding: 0;
        height:100%;
        overflow: hidden;
    }

    body{
        background-color: #1399ce;   
    }

    .editorBox{
        font-family: Courier New;
        font-size: 16px;
        float:left;
        width:50%;
        height:100%;    
    }

    .previewBox{  
        font-family: Courier New;
        font-size: 16px;
        float: right;
        width: 50%;
        height: 100%;    
        /*background-color: white;*/
        background-color: #fefefe;   
    }

    #previewArea{
        padding: 10px;
        width: 100%;
        height: 100%;
        overflow:auto;  
    }

    .md_editor{
        width:100%;
        height:100%;
        color: white;
        background-color: #202020;   
    }
    </style>
</head>
<body>
    <!-- 编辑区 -->
    <div class="editorBox">
        <textarea id="editor" class="md_editor">
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello

		
		</textarea>
    </div>

    <!-- 预览区 -->
    <div class="previewBox">
        <div id="previewArea"></div>
    </div>


</body>
</html>
```

**Comment by xbotao** [comment]
I add resize `app_main` function on document load and resize event.
The posts list page is OK. But the editing page have problem also on the firefox and other same kernel brower.

- add element id
  - [client/app.js#L8](https://github.com/newbiebt/hexo-admin/blob/master/client/app.js#L8) and [client/app.js#L19](https://github.com/newbiebt/hexo-admin/blob/master/client/app.js#L19)

- add event
  - [www/index.html#L14](https://github.com/newbiebt/hexo-admin/blob/master/www/index.html#L14)

**Comment by PirtleShell** [comment]
Everything should work properly on Firefox now. Will you try it out @xbotao?
from https://github.com/jaredly/hexo-admin/commit/879872444c88d1b4e26dd1e46788042eab94fca4

**Comment by xbotao** [comment]
It works properly. Thanks !
