### ISSUE TITLE
Input Chinese error

### ISSUE THREAD

**Issue by xbotao** [jaredly/hexo-admin#99]
If I input Chinese @ line 4, it will return to line 3.
the hexo-admin is the current github version.
like this:
```
1 fsdfsdafadsf
2 fasdfasdfsadfa
3
4 | 在此输入中文 input Chinese here  
```
the result is
```
1 fsdfsdafadsf
2 fasdfasdfsadfa
3 在此输入中文 input Chinese here  
```

or
```
1 fsdfsdafadsf
2 fasdfasdfsadfa
3 | 在此输入中文 input Chinese here  
```
the result is
```
1 fsdfsdafadsf
2 fasdfasdfsadfa在此输入中文 input Chinese here  
```

But the npm version `hexo-admin@2.1.0` dose not have this problem.

**Comment by xbotao** [comment]
And In the editor page, the button `F12` have no effect.

**Comment by PirtleShell** [comment]
I'm unable to reproduce your error.

![image](https://cloud.githubusercontent.com/assets/14897503/21628630/7f84ae0c-d1e6-11e6-8f40-b487ba6ee34e.png)

Leaving and coming back to the editor, viewing the prievew on the posts list, or refreshing the page does not result in the content changing.

The primary difference between the current github version and the npm version is that the github version uses the latest version of codemirror. The problem might have something to do with that, but I didn't see the error you explained when using the github version.

Also, what do you expect `F12` to do?

**Comment by xbotao** [comment]
Paste Chinese is not have this issue, it just appear on typing in Chinese by the Chinese typewriting.

`F12` will toggle the develop tools of firefox.

---
I will test it on ubuntu later.

**Comment by PirtleShell** [comment]
Hmm.. Sounds like a codemirror problem. Take a look around [its current issues](https://github.com/codemirror/CodeMirror/issues). Strange that you say it worked in the previous release. [Here](https://github.com/jaredly/hexo-admin/pull/87/commits/d79d73a5e11b0d80c89d17bb7dc034447b968e49#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L42) are the old and new codemirror versions.

**Comment by xbotao** [comment]
The follow HTML is ok in IE, Firefox and chrome.

```
<!doctype html>
<html>
<head>
    <meta charset="utf-8" /> 
    <title>Lazyboy Editor</title>
    <style>
    html, body{
        margin: 0;
        padding: 0;
        height:100%;
        overflow: hidden;
    }

    body{
        background-color: #1399ce;   
    }

    .editorBox{
        font-family: Courier New;
        font-size: 16px;
        float:left;
        width:50%;
        height:100%;    
    }

    .previewBox{  
        font-family: Courier New;
        font-size: 16px;
        float: right;
        width: 50%;
        height: 100%;    
        /*background-color: white;*/
        background-color: #fefefe;   
    }

    #previewArea{
        padding: 10px;
        width: 100%;
        height: 100%;
        overflow:auto;  
    }

    .md_editor{
        width:100%;
        height:100%;
        color: white;
        background-color: #202020;   
    }
    </style>
</head>
<body>
    <!-- 编辑区 -->
    <div class="editorBox">
        <textarea id="editor" class="md_editor">
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello
		hello

		
		</textarea>
    </div>

    <!-- 预览区 -->
    <div class="previewBox">
        <div id="previewArea"></div>
    </div>


</body>
</html>
```

**Comment by xbotao** [comment]
It's ok when tying Chinese on ubuntu.

**Comment by PirtleShell** [comment]
Were you able to figure out where the problem was with this?

**Comment by xbotao** [comment]
It apeared on the windows when tying in Chinese. I think the peoblem apear that beacuse the input method's working principle. When tying in a string, will get a key-down message, and char code is 229 at the beginning. After input the string, will get a key-message. The github editor has the same peoblem.



发自我的 iPhone

**Comment by xbotao** [comment]
I use firfox before，and I will test it on the Chrome later.

**Comment by xbotao** [comment]
I install `Hexo` and `Hexo-admin` with the vison on the github on another computer. 
There's no the problem. Sorry,! I guess the problem apears by my misoperation.
